// ==================================================================
// Lerninhalte: Englisches Elektro-Vokabular
// Du siehst deutsche Begriffe/Sätze und lernst die englischen Fachwörter.
// ==================================================================

(function() {

const LEVELS = {
  beginner:     { name: "Beginner (A1–A2)",       color: "#58cc02" },
  intermediate: { name: "Intermediate (B1)",       color: "#1cb0f6" },
  advanced:     { name: "Advanced (B2)",           color: "#ce82ff" },
  expert:       { name: "Expert / Technical (C1)", color: "#ff9600" },
};

// Schaltzeichen als Inline-SVG (immer scharf, kein externes Asset)
const SYMBOLS = {
  resistor:      `<svg viewBox="0 0 100 40"><line x1="0" y1="20" x2="20" y2="20" stroke="currentColor" stroke-width="2"/><rect x="20" y="10" width="60" height="20" fill="none" stroke="currentColor" stroke-width="2"/><line x1="80" y1="20" x2="100" y2="20" stroke="currentColor" stroke-width="2"/></svg>`,
  capacitor:     `<svg viewBox="0 0 100 40"><line x1="0" y1="20" x2="45" y2="20" stroke="currentColor" stroke-width="2"/><line x1="45" y1="5" x2="45" y2="35" stroke="currentColor" stroke-width="2"/><line x1="55" y1="5" x2="55" y2="35" stroke="currentColor" stroke-width="2"/><line x1="55" y1="20" x2="100" y2="20" stroke="currentColor" stroke-width="2"/></svg>`,
  inductor:      `<svg viewBox="0 0 100 40"><line x1="0" y1="20" x2="15" y2="20" stroke="currentColor" stroke-width="2"/><path d="M 15 20 Q 25 5 35 20 Q 45 5 55 20 Q 65 5 75 20 Q 85 5 85 20" fill="none" stroke="currentColor" stroke-width="2"/><line x1="85" y1="20" x2="100" y2="20" stroke="currentColor" stroke-width="2"/></svg>`,
  diode:         `<svg viewBox="0 0 100 40"><line x1="0" y1="20" x2="40" y2="20" stroke="currentColor" stroke-width="2"/><polygon points="40,8 40,32 60,20" fill="currentColor"/><line x1="60" y1="8" x2="60" y2="32" stroke="currentColor" stroke-width="2"/><line x1="60" y1="20" x2="100" y2="20" stroke="currentColor" stroke-width="2"/></svg>`,
  led:           `<svg viewBox="0 0 100 40"><line x1="0" y1="20" x2="40" y2="20" stroke="currentColor" stroke-width="2"/><polygon points="40,8 40,32 60,20" fill="currentColor"/><line x1="60" y1="8" x2="60" y2="32" stroke="currentColor" stroke-width="2"/><line x1="60" y1="20" x2="100" y2="20" stroke="currentColor" stroke-width="2"/><line x1="65" y1="5" x2="78" y2="0" stroke="currentColor" stroke-width="1.5"/><polygon points="74,-1 80,-1 77,4" fill="currentColor"/><line x1="72" y1="10" x2="85" y2="5" stroke="currentColor" stroke-width="1.5"/><polygon points="81,4 87,4 84,9" fill="currentColor"/></svg>`,
  transistor:    `<svg viewBox="0 0 100 60"><circle cx="50" cy="30" r="22" fill="none" stroke="currentColor" stroke-width="2"/><line x1="40" y1="15" x2="40" y2="45" stroke="currentColor" stroke-width="3"/><line x1="20" y1="30" x2="40" y2="30" stroke="currentColor" stroke-width="2"/><line x1="40" y1="20" x2="60" y2="10" stroke="currentColor" stroke-width="2"/><line x1="60" y1="10" x2="60" y2="0" stroke="currentColor" stroke-width="2"/><line x1="40" y1="40" x2="60" y2="50" stroke="currentColor" stroke-width="2"/><line x1="60" y1="50" x2="60" y2="60" stroke="currentColor" stroke-width="2"/><polygon points="55,42 60,50 50,48" fill="currentColor"/></svg>`,
  switch:        `<svg viewBox="0 0 100 40"><line x1="0" y1="20" x2="30" y2="20" stroke="currentColor" stroke-width="2"/><circle cx="32" cy="20" r="2" fill="currentColor"/><line x1="32" y1="20" x2="65" y2="8" stroke="currentColor" stroke-width="2"/><circle cx="68" cy="20" r="2" fill="currentColor"/><line x1="68" y1="20" x2="100" y2="20" stroke="currentColor" stroke-width="2"/></svg>`,
  ground:        `<svg viewBox="0 0 60 60"><line x1="30" y1="0" x2="30" y2="25" stroke="currentColor" stroke-width="2"/><line x1="10" y1="25" x2="50" y2="25" stroke="currentColor" stroke-width="3"/><line x1="18" y1="35" x2="42" y2="35" stroke="currentColor" stroke-width="2"/><line x1="24" y1="45" x2="36" y2="45" stroke="currentColor" stroke-width="2"/></svg>`,
  battery:       `<svg viewBox="0 0 100 40"><line x1="0" y1="20" x2="40" y2="20" stroke="currentColor" stroke-width="2"/><line x1="40" y1="5" x2="40" y2="35" stroke="currentColor" stroke-width="3"/><line x1="50" y1="12" x2="50" y2="28" stroke="currentColor" stroke-width="2"/><line x1="55" y1="5" x2="55" y2="35" stroke="currentColor" stroke-width="3"/><line x1="65" y1="12" x2="65" y2="28" stroke="currentColor" stroke-width="2"/><line x1="65" y1="20" x2="100" y2="20" stroke="currentColor" stroke-width="2"/></svg>`,
  fuse:          `<svg viewBox="0 0 100 40"><line x1="0" y1="20" x2="20" y2="20" stroke="currentColor" stroke-width="2"/><rect x="20" y="12" width="60" height="16" fill="none" stroke="currentColor" stroke-width="2"/><line x1="20" y1="20" x2="80" y2="20" stroke="currentColor" stroke-width="2"/><line x1="80" y1="20" x2="100" y2="20" stroke="currentColor" stroke-width="2"/></svg>`,
  bulb:          `<svg viewBox="0 0 60 60"><circle cx="30" cy="30" r="18" fill="none" stroke="currentColor" stroke-width="2"/><line x1="17" y1="17" x2="43" y2="43" stroke="currentColor" stroke-width="2"/><line x1="43" y1="17" x2="17" y2="43" stroke="currentColor" stroke-width="2"/></svg>`,
  motor:         `<svg viewBox="0 0 60 60"><circle cx="30" cy="30" r="20" fill="none" stroke="currentColor" stroke-width="2"/><text x="30" y="37" font-size="20" font-weight="bold" text-anchor="middle" fill="currentColor">M</text></svg>`,
  transformer:   `<svg viewBox="0 0 120 60"><line x1="0" y1="30" x2="30" y2="30" stroke="currentColor" stroke-width="2"/><path d="M 30 30 Q 35 20 40 30 Q 45 20 50 30 Q 55 20 55 30" fill="none" stroke="currentColor" stroke-width="2"/><line x1="60" y1="10" x2="60" y2="50" stroke="currentColor" stroke-width="2"/><line x1="64" y1="10" x2="64" y2="50" stroke="currentColor" stroke-width="2"/><path d="M 69 30 Q 74 20 79 30 Q 84 20 89 30 Q 94 20 94 30" fill="none" stroke="currentColor" stroke-width="2"/><line x1="94" y1="30" x2="120" y2="30" stroke="currentColor" stroke-width="2"/></svg>`,
};

// ==================================================================
// LEKTIONEN – Englisches Vokabular in Themenblöcken
// ==================================================================
const LESSONS = [

  // ============ BASICS (Grundlagen) ============
  {
    id: "basics_1",
    thema: "Basics",
    titel: "Basic Quantities",
    icon: "⚡",
    levels: ["beginner", "intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Spannung", back: "voltage  🔊  /ˈvəʊl.tɪdʒ/\nBeispiel: 'The voltage is 230 volts.'" },
      { type: "flashcard", front: "Strom / Stromstärke", back: "current  🔊  /ˈkʌr.ənt/\nBeispiel: 'A current of 2 amperes flows through the wire.'" },
      { type: "flashcard", front: "Widerstand", back: "resistance  🔊  /rɪˈzɪs.təns/\nBeispiel: 'The resistance is measured in ohms.'" },
      { type: "flashcard", front: "Leistung", back: "power  🔊  /ˈpaʊ.ər/\nBeispiel: 'The power consumption is 60 watts.'" },
      { type: "mc", question: "Wie heißt „Spannung“ auf Englisch?", options: ["current", "voltage", "power", "resistance"], correct: 1 },
      { type: "mc", question: "Wie heißt „Strom“ auf Englisch?", options: ["power", "voltage", "current", "load"], correct: 2 },
      { type: "mc", question: "„Resistance“ bedeutet …", options: ["Leistung", "Widerstand", "Spannung", "Ladung"], correct: 1 },
      { type: "mc", question: "„Power“ bedeutet …", options: ["Strom", "Spannung", "Widerstand", "Leistung"], correct: 3 },
      { type: "cloze", text: "Voltage is measured in ___.", answer: "volts" },
      { type: "cloze", text: "Current is measured in ___.", answer: "amperes", altAnswers: ["amps", "ampere"] },
    ],
  },
  {
    id: "basics_2",
    thema: "Basics",
    titel: "Units & Symbols",
    icon: "📐",
    levels: ["beginner", "intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Volt (V)", back: "volt – die Einheit der Spannung (voltage).\nExample: 'a nine-volt battery'" },
      { type: "flashcard", front: "Ampere (A)", back: "ampere / amp – die Einheit des Stroms (current)." },
      { type: "flashcard", front: "Ohm (Ω)", back: "ohm – die Einheit des Widerstands (resistance)." },
      { type: "flashcard", front: "Watt (W)", back: "watt – die Einheit der Leistung (power)." },
      { type: "flashcard", front: "Farad (F)", back: "farad – die Einheit der Kapazität (capacitance)." },
      { type: "mc", question: "Which unit measures voltage?", options: ["ampere", "ohm", "volt", "watt"], correct: 2 },
      { type: "mc", question: "Which unit measures power?", options: ["volt", "watt", "farad", "henry"], correct: 1 },
      { type: "mc", question: "The unit of capacitance is the …", options: ["henry", "ohm", "farad", "coulomb"], correct: 2 },
      { type: "cloze", text: "One kilowatt equals 1000 ___.", answer: "watts", altAnswers: ["watt"] },
      { type: "cloze", text: "Resistance is measured in ___.", answer: "ohms", altAnswers: ["ohm"] },
    ],
  },
  {
    id: "basics_3",
    thema: "Basics",
    titel: "Ohm's Law & Sentences",
    icon: "🧮",
    levels: ["intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Ohmsches Gesetz", back: "Ohm's Law:  V = I · R\n(Voltage = Current × Resistance)" },
      { type: "flashcard", front: "Ladung", back: "charge  🔊  /tʃɑːdʒ/  – Einheit: coulomb (C)" },
      { type: "flashcard", front: "Energie / Arbeit", back: "energy / work  – Einheit: joule (J) oder kilowatt-hour (kWh)" },
      { type: "mc", question: "„Voltage equals current times resistance“ ist die Formel für …", options: ["Kirchhoff's Law", "Faraday's Law", "Ohm's Law", "Newton's Law"], correct: 2 },
      { type: "cloze", text: "According to Ohm's Law: V = I × ___.", answer: "R" },
      { type: "cloze", text: "Electrical ___ is measured in watts.", answer: "power" },
      { type: "cloze", text: "The battery has a ___ of 12 volts.", answer: "voltage" },
      { type: "calc", question: "V = 12 V, R = 4 Ω. Calculate the current I in amperes.", answer: 3, unit: "A", hint: "I = V / R" },
      { type: "calc", question: "I = 2 A, R = 5 Ω. Calculate the voltage V in volts.", answer: 10, unit: "V", hint: "V = I · R" },
      { type: "calc", question: "V = 230 V, I = 10 A. Calculate the power P in watts.", answer: 2300, unit: "W", hint: "P = V · I" },
    ],
  },

  // ============ COMPONENTS (Bauteile) ============
  {
    id: "comp_1",
    thema: "Components",
    titel: "Passive Components",
    icon: "🔩",
    levels: ["beginner", "intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Widerstand (Bauteil)", back: "resistor  🔊  /rɪˈzɪs.tər/" },
      { type: "flashcard", front: "Kondensator", back: "capacitor  🔊  /kəˈpæs.ɪ.tər/" },
      { type: "flashcard", front: "Spule / Induktivität", back: "inductor  🔊  /ɪnˈdʌk.tər/  (auch: coil)" },
      { type: "flashcard", front: "Transformator", back: "transformer  🔊  /trænsˈfɔː.mər/" },
      { type: "mc", question: "Wie heißt „Kondensator“ auf Englisch?", options: ["conductor", "capacitor", "resistor", "connector"], correct: 1 },
      { type: "mc", question: "„Inductor“ bedeutet …", options: ["Widerstand", "Kondensator", "Spule", "Transformator"], correct: 2 },
      { type: "match", instruction: "Which component is shown? (English name)", symbol: SYMBOLS.resistor, options: ["capacitor", "resistor", "inductor", "diode"], correct: 1 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.capacitor, options: ["resistor", "battery", "capacitor", "inductor"], correct: 2 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.inductor, options: ["resistor", "capacitor", "inductor", "fuse"], correct: 2 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.transformer, options: ["motor", "generator", "transformer", "inductor"], correct: 2 },
      { type: "cloze", text: "A ___ stores electrical charge.", answer: "capacitor" },
      { type: "cloze", text: "A ___ limits the flow of current.", answer: "resistor" },
    ],
  },
  {
    id: "comp_2",
    thema: "Components",
    titel: "Semiconductors",
    icon: "💡",
    levels: ["intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Diode", back: "diode  🔊  /ˈdaɪ.əʊd/\nlässt Strom nur in einer Richtung durch." },
      { type: "flashcard", front: "Leuchtdiode", back: "LED (light-emitting diode)  🔊  /ˌel.iːˈdiː/" },
      { type: "flashcard", front: "Transistor", back: "transistor  🔊  /trænˈzɪs.tər/\nAnschlüsse: base, collector, emitter (BJT) oder gate, drain, source (FET)" },
      { type: "flashcard", front: "Integrierter Schaltkreis (IC)", back: "integrated circuit (IC)" },
      { type: "mc", question: "„LED“ steht für …", options: ["light-electric device", "low-energy diode", "light-emitting diode", "low-emission device"], correct: 2 },
      { type: "mc", question: "Which term means „Halbleiter“?", options: ["conductor", "semiconductor", "insulator", "receptor"], correct: 1 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.diode, options: ["capacitor", "diode", "resistor", "switch"], correct: 1 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.led, options: ["diode", "photocell", "LED", "bulb"], correct: 2 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.transistor, options: ["diode", "IC", "transistor", "relay"], correct: 2 },
      { type: "cloze", text: "A diode allows current to flow in only one ___.", answer: "direction" },
      { type: "cloze", text: "The three terminals of a bipolar transistor are base, ___ and emitter.", answer: "collector" },
    ],
  },
  {
    id: "comp_3",
    thema: "Components",
    titel: "Electromechanical Parts",
    icon: "⚙️",
    levels: ["intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Schalter", back: "switch  🔊  /swɪtʃ/" },
      { type: "flashcard", front: "Relais", back: "relay  🔊  /ˈriː.leɪ/" },
      { type: "flashcard", front: "Motor", back: "motor  🔊  /ˈməʊ.tər/  (auch: electric motor)" },
      { type: "flashcard", front: "Generator", back: "generator  🔊  /ˈdʒen.ə.reɪ.tər/" },
      { type: "flashcard", front: "Sicherung", back: "fuse  🔊  /fjuːz/" },
      { type: "flashcard", front: "Glühbirne / Lampe", back: "light bulb / lamp" },
      { type: "mc", question: "„Fuse“ bedeutet …", options: ["Stecker", "Schalter", "Sicherung", "Buchse"], correct: 2 },
      { type: "mc", question: "„Relay“ bedeutet …", options: ["Motor", "Relais", "Schalter", "Zähler"], correct: 1 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.switch, options: ["switch", "fuse", "relay", "diode"], correct: 0 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.fuse, options: ["resistor", "fuse", "capacitor", "wire"], correct: 1 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.bulb, options: ["motor", "light bulb", "LED", "buzzer"], correct: 1 },
      { type: "match", instruction: "Which component is shown?", symbol: SYMBOLS.motor, options: ["meter", "motor", "generator", "battery"], correct: 1 },
      { type: "cloze", text: "When the current is too high, the ___ blows and breaks the circuit.", answer: "fuse" },
    ],
  },

  // ============ CIRCUITS (Schaltungen) ============
  {
    id: "circ_1",
    thema: "Circuits",
    titel: "Circuit Basics",
    icon: "🔗",
    levels: ["beginner", "intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Stromkreis", back: "circuit  🔊  /ˈsɜː.kɪt/" },
      { type: "flashcard", front: "Schaltplan", back: "circuit diagram / schematic  🔊  /skɪˈmæt.ɪk/" },
      { type: "flashcard", front: "Leitung / Kabel", back: "wire (dünn) / cable (mehrere Adern)" },
      { type: "flashcard", front: "Reihenschaltung", back: "series circuit  🔊  /ˈsɪə.riːz/" },
      { type: "flashcard", front: "Parallelschaltung", back: "parallel circuit  🔊  /ˈpær.ə.lel/" },
      { type: "flashcard", front: "Knoten", back: "node  🔊  /nəʊd/" },
      { type: "flashcard", front: "Masche", back: "loop  🔊  /luːp/" },
      { type: "mc", question: "„Circuit diagram“ ist deutsch …", options: ["Verkabelung", "Stromkreis", "Schaltplan", "Aufbau"], correct: 2 },
      { type: "mc", question: "In a ___ circuit, the current is the same through every component.", options: ["parallel", "series", "short", "open"], correct: 1 },
      { type: "cloze", text: "When you press the switch, the ___ is closed and current flows.", answer: "circuit" },
      { type: "cloze", text: "In a parallel circuit, the voltage is the same across each ___.", answer: "component", altAnswers: ["branch", "element"] },
    ],
  },
  {
    id: "circ_2",
    thema: "Circuits",
    titel: "Circuit States",
    icon: "🔀",
    levels: ["intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "geschlossener Stromkreis", back: "closed circuit – current can flow" },
      { type: "flashcard", front: "offener Stromkreis", back: "open circuit – current cannot flow" },
      { type: "flashcard", front: "Kurzschluss", back: "short circuit  🔊  /ˈʃɔːt ˌsɜː.kɪt/" },
      { type: "flashcard", front: "Erdschluss / Fehlerstrom", back: "ground fault / earth fault" },
      { type: "flashcard", front: "Überlast", back: "overload  🔊  /ˌəʊ.vərˈləʊd/" },
      { type: "mc", question: "„Short circuit“ heißt auf Deutsch …", options: ["Kurzschluss", "Kurzleitung", "Trennstelle", "Reihenschluss"], correct: 0 },
      { type: "mc", question: "Wenn kein Strom fließt, ist der Stromkreis …", options: ["closed", "open", "loaded", "shorted"], correct: 1 },
      { type: "cloze", text: "When two wires touch and cause a very high current, that is a ___ circuit.", answer: "short" },
      { type: "cloze", text: "Turning the switch on ___ the circuit.", answer: "closes", altAnswers: ["close"] },
    ],
  },
  {
    id: "circ_3",
    thema: "Circuits",
    titel: "AC / DC & Signals",
    icon: "〰️",
    levels: ["advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Wechselspannung / -strom", back: "alternating current (AC)  🔊  /ˈɔːl.tə.neɪ.tɪŋ/" },
      { type: "flashcard", front: "Gleichspannung / -strom", back: "direct current (DC)  🔊  /dɪˈrekt/" },
      { type: "flashcard", front: "Frequenz", back: "frequency  🔊  /ˈfriː.kwən.si/ – Einheit: hertz (Hz)" },
      { type: "flashcard", front: "Wellenform", back: "waveform  🔊  /ˈweɪv.fɔːm/" },
      { type: "flashcard", front: "Phase", back: "phase  🔊  /feɪz/" },
      { type: "mc", question: "„AC“ steht für …", options: ["Active Current", "Alternating Current", "Applied Current", "Automatic Circuit"], correct: 1 },
      { type: "mc", question: "„DC“ steht für …", options: ["Dynamic Current", "Direct Current", "Double Circuit", "Digital Charge"], correct: 1 },
      { type: "cloze", text: "Batteries produce ___ current, but wall outlets deliver AC.", answer: "direct" },
      { type: "cloze", text: "The mains ___ in Europe is 50 hertz.", answer: "frequency" },
    ],
  },

  // ============ INSTALLATION ============
  {
    id: "inst_1",
    thema: "Installation",
    titel: "Wires & Cables",
    icon: "🔌",
    levels: ["beginner", "intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Leiter (Ader)", back: "wire / conductor  🔊  /kənˈdʌk.tər/" },
      { type: "flashcard", front: "Kabel (mehradrig)", back: "cable  🔊  /ˈkeɪ.bəl/" },
      { type: "flashcard", front: "Isolation / Isolierung", back: "insulation  🔊  /ˌɪn.sjʊˈleɪ.ʃən/" },
      { type: "flashcard", front: "Isolator (Bauteil)", back: "insulator  🔊  /ˈɪn.sjʊ.leɪ.tər/" },
      { type: "flashcard", front: "Stecker", back: "plug  🔊  /plʌɡ/" },
      { type: "flashcard", front: "Steckdose", back: "socket / outlet  🔊  /ˈaʊt.let/ (US)" },
      { type: "flashcard", front: "Kabelkanal / Rohr", back: "conduit  🔊  /ˈkɒn.dʒu.ɪt/" },
      { type: "mc", question: "„Insulation“ bedeutet …", options: ["Leitung", "Isolierung", "Erdung", "Verbindung"], correct: 1 },
      { type: "mc", question: "„Outlet“ ist die amerikanische Bezeichnung für …", options: ["Stecker", "Kabel", "Steckdose", "Sicherung"], correct: 2 },
      { type: "cloze", text: "Insert the ___ into the socket.", answer: "plug" },
      { type: "cloze", text: "Copper is a very good ___ of electricity.", answer: "conductor" },
    ],
  },
  {
    id: "inst_2",
    thema: "Installation",
    titel: "Phase, Neutral & Ground",
    icon: "🏠",
    levels: ["intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Außenleiter / Phase (L)", back: "line (L) / phase / hot wire (US, umgangssprachlich)" },
      { type: "flashcard", front: "Neutralleiter (N)", back: "neutral  🔊  /ˈnjuː.trəl/  (Farbe: blau)" },
      { type: "flashcard", front: "Schutzleiter (PE)", back: "protective earth (PE) / ground (US)  – Farbe: grün-gelb" },
      { type: "flashcard", front: "Erde / Erdung", back: "earth (UK) / ground (US)" },
      { type: "flashcard", front: "Drehstrom", back: "three-phase power / three-phase current" },
      { type: "mc", question: "The color of the protective earth wire is …", options: ["blue", "brown", "green-yellow", "black"], correct: 2 },
      { type: "mc", question: "„Neutral“ auf Deutsch …", options: ["Außenleiter", "Neutralleiter", "Schutzleiter", "Erde"], correct: 1 },
      { type: "match", instruction: "Which symbol is this?", symbol: SYMBOLS.ground, options: ["neutral", "phase", "ground / earth", "antenna"], correct: 2 },
      { type: "cloze", text: "In an emergency, current flows through the ___ wire to protect people.", answer: "ground", altAnswers: ["earth"] },
      { type: "cloze", text: "Three-phase power uses three ___ conductors plus a neutral.", answer: "line", altAnswers: ["phase"] },
    ],
  },
  {
    id: "inst_3",
    thema: "Installation",
    titel: "Protection Devices",
    icon: "🛡️",
    levels: ["intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Leitungsschutzschalter (LS)", back: "circuit breaker  🔊  /ˈsɜː.kɪt ˌbreɪ.kər/" },
      { type: "flashcard", front: "FI-Schutzschalter", back: "RCD (residual-current device) / GFCI (US, ground-fault circuit interrupter)" },
      { type: "flashcard", front: "Sicherungskasten", back: "fuse box / distribution board / consumer unit (UK)" },
      { type: "flashcard", front: "Überspannungsschutz", back: "surge protector  🔊  /sɜːdʒ prəˈtek.tər/" },
      { type: "flashcard", front: "auslösen (Sicherung)", back: "to trip  🔊  /trɪp/\nExample: 'The breaker tripped when I turned on the heater.'" },
      { type: "mc", question: "„Circuit breaker“ auf Deutsch …", options: ["FI-Schalter", "Leitungsschutzschalter", "Trennschalter", "Hauptschalter"], correct: 1 },
      { type: "mc", question: "„RCD“ / „GFCI“ schützt vor …", options: ["over-voltage", "residual (leakage) currents", "over-load", "short circuits only"], correct: 1 },
      { type: "cloze", text: "If there is a fault, the circuit breaker will ___.", answer: "trip" },
      { type: "cloze", text: "Never work on live circuits without switching off the ___.", answer: "power", altAnswers: ["breaker", "circuit"] },
    ],
  },

  // ============ MEASUREMENT & TOOLS ============
  {
    id: "meas_1",
    thema: "Measurement",
    titel: "Meters & Measurements",
    icon: "📊",
    levels: ["beginner", "intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Multimeter", back: "multimeter  🔊  /ˈmʌl.tiˌmiː.tər/" },
      { type: "flashcard", front: "Oszilloskop", back: "oscilloscope  🔊  /əˈsɪl.ə.skəʊp/" },
      { type: "flashcard", front: "Voltmeter", back: "voltmeter" },
      { type: "flashcard", front: "Amperemeter", back: "ammeter  🔊  /ˈæm.iː.tər/" },
      { type: "flashcard", front: "Messung / Messwert", back: "measurement / reading" },
      { type: "flashcard", front: "Messfühler / Prüfspitze", back: "probe  🔊  /prəʊb/" },
      { type: "mc", question: "Wie heißt „Oszilloskop“ auf Englisch?", options: ["oscilloscope", "voltmeter", "oscillator", "spectrometer"], correct: 0 },
      { type: "mc", question: "„Reading“ (im Messkontext) heißt …", options: ["Ablesung / Messwert", "Bedienung", "Anzeige-Skala", "Kalibrierung"], correct: 0 },
      { type: "cloze", text: "Use a multimeter to ___ the voltage.", answer: "measure" },
      { type: "cloze", text: "Connect the ___ to the two points you want to measure.", answer: "probes", altAnswers: ["probe"] },
    ],
  },
  {
    id: "meas_2",
    thema: "Measurement",
    titel: "Tools & Workshop",
    icon: "🧰",
    levels: ["beginner", "intermediate", "advanced", "expert"],
    exercises: [
      { type: "flashcard", front: "Schraubendreher", back: "screwdriver  🔊  /ˈskruːˌdraɪ.vər/" },
      { type: "flashcard", front: "Zange", back: "pliers  🔊  /ˈplaɪ.əz/  (immer im Plural)" },
      { type: "flashcard", front: "Abisolierzange", back: "wire stripper  🔊  /ˈwaɪə ˌstrɪp.ər/" },
      { type: "flashcard", front: "Seitenschneider", back: "side cutter / diagonal pliers" },
      { type: "flashcard", front: "Lötkolben", back: "soldering iron  🔊  /ˈsɒl.dər.ɪŋ ˌaɪən/" },
      { type: "flashcard", front: "Klebeband / Isolierband", back: "electrical tape / insulating tape" },
      { type: "mc", question: "„Pliers“ bedeutet …", options: ["Zange", "Meißel", "Feile", "Schraubenschlüssel"], correct: 0 },
      { type: "mc", question: "„Soldering iron“ bedeutet …", options: ["Bügeleisen", "Schweißgerät", "Lötkolben", "Heißluftpistole"], correct: 2 },
      { type: "cloze", text: "Use a wire ___ to remove insulation from the end of the wire.", answer: "stripper" },
      { type: "cloze", text: "You need a ___ to tighten the screws.", answer: "screwdriver" },
    ],
  },

];

// Für globalen Zugriff im Browser
window.APP_DATA = { LEVELS, LESSONS, SYMBOLS };

})();
